# Please check the parameters, and adjust them according to your circumstance

# ================== Parameters for fyraflow variant sub-modules ==================

## Project Name
PROJECT: 40japonicus

## Fission yeast species of re-sequencing analysis
SPECIES: S_japonicus # "S_pombe" or "S_octosporus_ref" or "S_octosporus_Tong" or "S_japonicus" or "S_versatilis" or "S_osmophilus" or "S_cryophilus"

## The path of fastq files
READSPATH: /data/b/resource/Short_Reads/Sjaponicus

## The working directory
WORKPATH: /data/b/jgs/variant_calling/Sjaponicus

## The sample list file
SAMPLE: /data/b/jgs/variant_calling/Spombe/wild_strain_5_21.6.21.list

## The final output directory
OUTPUTPATH: /data/b/jgs/variant_calling/Sjaponicus
