# Please check the parameters, and adjust them according to your circumstance

# ================== Parameters for fyraflow variant sub-modules ==================

## Project Name
PROJECT: 141_octosporus_joint

## Fission yeast species of re-sequencing analysis
SPECIES: S_octosporus_ref # "S_pombe" or "S_octosporus_ref" or "S_octosporus_Tong" or "S_japonicus" or "S_versatilis" or "S_osmophilus" or "S_cryophilus"

## The path of fastq files
READSPATH: /data/b/resource/Short_Reads/Soctosporus

## The working directory
WORKPATH: /data/b/jgs/variant_calling/Soctosporus_ref

## The sample list file
SAMPLE: /data/b/jgs/variant_calling/Sversatilis_NGS/21.04_51versatilis.list

## The final output directory
OUTPUTPATH: /data/b/jgs/variant_calling/Soctosporus_ref
